PRIVACY POLICY:
WEBSITE VISITORS:

Like most website operators, marsawaves. collects non-personally identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. , marsawaves  purpose in collecting non-personally identifying information is to better understand how , marsawaves’s visitors use its website. From time to time, , marsawaves may release non-personally identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.
 marsawaves also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged-in users and for users leaving comments on , marsawaves.com blogs/sites. , marsawaves only discloses logged-in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that commenter IP addresses and email addresses are visible and disclosed to the administrators of the blog/site where the comment was left.

GATHERING OF PERSONALLY-IDENTIFYING INFORMATION
Certain visitors to , marsawavs’s websites choose to interact with marsawaves in ways that require marsawaves to gather personally identifying information. The amount and type of information that marsawaves gathers depend on the nature of the interaction. For example, we ask visitors who sign up at marsawaves.com to provide a username and email address. Those who engage in transactions with marsawaves are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case marsawaves collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with marsawaves.  marsawaves does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.
AGGREGATED STATISTICS
marsawaves may collect statistics about the behavior of visitors to its websites. , marsawaves may display this information publicly or provide it to others. However,  marsawaves does not disclose personally-identifying information other than as described below.

PROTECTION OF CERTAIN PERSONALLY-IDENTIFYING INFORMATION
marsawaves discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors, and affiliated organizations that (i) need to know that information in order to process it on marsawaves’s behalf or to provide services available at marsawaves’s websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors, and affiliated organizations may be located outside of your home country; by using marsawaves’s websites, you consent to the transfer of such information to them. marsawaves will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors, and affiliated organizations, as described above, marsawaves discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order, or another governmental request, or when marsawaves believes in good faith that disclosure is reasonably necessary to protect the property or rights of marsawaves, third parties or the public at large. If you are a registered user of the marsawaves website and have supplied your email address, marsawaves may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with marsawaves and our products. If you send us a request (for example via email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. marsawaves takes all measures reasonably necessary to protect against the unauthorized access, use, alteration, or destruction of potentially personally-identifying and personally-identifying information.
COOKIES
A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. marsawaves uses cookies to help marsawaves identify and track visitors, their usage of the marsawaves website, and their website access preferences. marsawaves visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using marsawaves’s websites, with the drawback that certain features of marsawaves’s websites may not function properly without the aid of cookies.
BUSINESS TRANSFERS
If marsawaves, or substantially all of its assets, were acquired, or in the unlikely event that marsawaves goes out of business or enters bankruptcy, user information would be one of the assets that are transferred or acquired by a third party. You acknowledge that such transfers may occur and that any acquirer of marsawaves may continue to use your personal information as set forth in this policy.
ADS
Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by marsawaves and does not cover the use of cookies by any advertisers.
Google Adsense and the DoubleClick DART Cookie
Google, as a third-party advertisement vendor, uses cookies to serve ads on this site. The use of DART cookies by Google enables them to serve adverts to visitors that are based on their visits to this website as well as other sites on the internet.
To opt-out of the DART cookies, you may visit the Google ad and content network privacy policy at the following URL http://www.google.com/privacy_ads.html Tracking of users through the DART cookie mechanisms are subject to Google’s own privacy policies.
Other Third Party ad servers or ad networks may also use cookies to track users’ activities on this website to measure advertisement effectiveness and other reasons that will be provided in their own privacy policies, marsawaves has no access or control over these cookies that may be used by third party advertisers.
Information shared with a payment provider to process payments includes:
•	Name
•	Email
•	Address
•	Phone
•	City/State/Zip
•	Unique payment identifier
•	Payment provider identifier
PRIVACY POLICY CHANGES
Although most changes are likely to be minor, marsawaves may change its Privacy Policy from time to time, and marsawaves’s sole discretion. PM-Tricks encourages visitors to frequently check this page for any changes to its Privacy Policy. If you have a marsawaves.com account, you might also receive an alert informing you of these changes. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of the such change.
